### ISSUE TITLE
Authtoken Issue

### ISSUE THREAD

**Issue by Malted-Wheaties** [Malted-Wheaties/EduLinkPy#1]
`EduLink.Login` returns status `error` with reason `No authtoken supplied`, when one has not already been provided by the server.
On the official EduLink website, `EduLink.Login` is posted to the server with no authtoken included, and gets a full response back, which includes the session authtoken for use in subsequent requests.

**Comment by CharlieWhile13** [comment]
Resolved in https://github.com/Malted-Wheaties/EduLinkPy/pull/2
